FROM registry.access.redhat.com/ubi9/python-311

LABEL description="Webserver en Python puro con http.server"

WORKDIR /opt/app-root/src

# Copiamos el código con el usuario no root de la imagen (1001)
COPY --chown=1001:0 server.py .

ENV PORT=8080 \
    PYTHONUNBUFFERED=1

EXPOSE 8080
USER 1001

CMD ["python", "server.py"]
